steps:
  - name: rocker/r-base
    args:
      - Rscript
      - -e
      - "library(googlesheets4)\nlibrary(googleCloudRunner)\nlibrary(googleAuthR)\nlibrary(httr)\nlibrary(jsonlite)\nlibrary(dplyr)\n\n#
        read the keys\nSys.setenv('APCA-API-KEY-ID' = \"CKY4IBD93ZMGYI554GJ0\")\nSys.setenv('APCA-API-SECRET-KEY'
        = \"qDm0P3JcHUYWtOHgEKL0QHlh79h0QytaXi97gliW\")\n\nGCE_AUTH_FILE=\"alpacaportfoliobalancing-44800fde91c8.json\"\nGCE_DEFAULT_PROJECT_ID=\"104832190364286526802\"\nGCS_DEFAULT_BUCKET=\"alpaca_code_repositotory_v1\"\nCR_REGION=\"northamerica-northeast1\"\nCR_BUILD_EMAIL=portfolio-rebalancing-v1@alpacaportfoliobalancing.iam.gserviceaccount.com\n\n\n\nALPACA_API_ID
        <- Sys.getenv(\"APCA-API-KEY-ID\")\nALPACA_API_SECRET <- Sys.getenv(\"APCA-API-SECRET-KEY\")\n\n#
        fetch the broker URL\nbroker_url = \"https://broker-api.sandbox.alpaca.markets/\"\naccounts_url
        = \"v1/accounts\"\nassets_url = \"v1/assets/\"\ntrading_url = \"/v1/trading/accounts/\"
        #You need to add {account_id}\"/positions\"\npositions_url = \"/positions\"
        #You need to add {account_id}\"/positions\"\nrebalancing_url = \"v1/rebalancing/portfolios\"\nportfolio_url
        =\"v1/rebalancing/portfolios\"\nsubscriptions_url = \"v1/rebalancing/subscriptions\"\n\n###
        GET THE RISK PROFILES ####\n#Read clients google sheets data into R\nclients
        <- read_sheet('https://docs.google.com/spreadsheets/d/1U2EqhZDBF_hLTnsW4FBVyC3_ZTbzMoXhMzlZWfzOv0I/edit#gid=0')\nclients
        <- as.data.frame(clients)\nclients <- clients[!is.na(clients$$account_ID),]\nclients$$risk_profile_previous_day[is.na(clients$$risk_profile_previous_day)]
        <- 0\n\n\n#Get all accounts from Alpaqa broker API & merge it with risk profiles\nget_accounts
        <- GET(url = paste(broker_url,accounts_url, sep=\"\"), \n           authenticate(ALPACA_API_ID,
        ALPACA_API_SECRET, type=\"basic\"))\n\nalpaqa_accounts = fromJSON(rawToChar(get_accounts$$content))\nactive_clients
        <- merge(clients, alpaqa_accounts, by.x=(\"account_ID\"), by.y=\"account_number\",
        all.x=TRUE)\n#Uses accounts with new risk profile\nto_allocate <- active_clients[!(active_clients$$risk_profile
        == active_clients$$risk_profile_previous_day),]\n\n######  ASSIGN A PORTFOLIO
        \ ######\n#retrieves all the portfolios\nget_portfolios <- GET(url = paste(broker_url,portfolio_url,
        sep=\"\"), \n                    authenticate(ALPACA_API_ID, ALPACA_API_SECRET,
        type=\"basic\"))\nportfolios = fromJSON(rawToChar(get_portfolios$$content))\nprint(portfolios)\n\nfor
        (i in unique(to_allocate$$account_ID)){\n  print(i)\n  \n  account <- active_clients$$id[active_clients$$account_ID==i]\n
        \ portfolio_profile <- paste(\"port\",  active_clients$$risk_profile[active_clients$$account_ID==i],
        sep=\"\")\n  port_id <- portfolios$$id[portfolios$$name ==portfolio_profile]\n
        \ \n  subscription_body <- list(account_id = account,\n                            portfolio_id
        = port_id)\n  \n  subscription <- POST(url = paste(broker_url,rebalancing_sub_url,sep=\"\"),\n
        \                      body = subscription_body, encode = \"json\",\n                       authenticate(ALPACA_API_ID,
        ALPACA_API_SECRET, type=\"basic\"))\n  \n  content(subscription)\n}\n\n"
#Generated by googleCloudRunner::cr_build_write at 2022-12-13 18:56:47
